local recharge = {
[1] = {ID=1,RMB=6,Reward=60,SpecialReward=0,icon="UI_shop_dia01.png",ProductId_ry="com.rongyao.cs.p6",ProductId_rydxc="com.rongyaodxc.cs.p6",ProductId_rygs="com.rongyaogs.cs.p6",type=0},
[2] = {ID=2,RMB=30,Reward=300,SpecialReward=30,icon="UI_shop_dia02.png",ProductId_ry="com.rongyao.cs.p30",ProductId_rydxc="com.rongyaodxc.cs.p30",ProductId_rygs="com.rongyaogs.cs.p30",type=0},
[3] = {ID=3,RMB=98,Reward=980,SpecialReward=150,icon="UI_shop_dia03.png",ProductId_ry="com.rongyao.cs.p98",ProductId_rydxc="com.rongyaodxc.cs.p98",ProductId_rygs="com.rongyaogs.cs.p98",type=0},
[4] = {ID=4,RMB=198,Reward=1980,SpecialReward=330,icon="UI_shop_dia04.png",ProductId_ry="com.rongyao.cs.p198",ProductId_rydxc="com.rongyaodxc.cs.p198",ProductId_rygs="com.rongyaogs.cs.p198",type=0},
[5] = {ID=5,RMB=328,Reward=3280,SpecialReward=660,icon="UI_shop_dia04.png",ProductId_ry="com.rongyao.cs.p328",ProductId_rydxc="com.rongyaodxc.cs.p328",ProductId_rygs="com.rongyaogs.cs.p328",type=0},
[6] = {ID=6,RMB=648,Reward=6480,SpecialReward=1260,icon="UI_shop_dia04.png",ProductId_ry="com.rongyao.cs.p648",ProductId_rydxc="com.rongyaodxc.cs.p648",ProductId_rygs="com.rongyaogs.cs.p648",type=0},
[7] = {ID=7,RMB=30,Reward=250,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.monthcard30",ProductId_rydxc="com.rongyaodxc.cs.monthcard30",ProductId_rygs="com.rongyaogs.cs.monthcard30",type=1},
[10] = {ID=10,RMB=20,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard10",ProductId_rydxc="com.rongyaodxc.cs.weekcard10",ProductId_rygs="com.rongyaogs.cs.weekcard10",type=2},
[20] = {ID=20,RMB=100,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard20",ProductId_rydxc="com.rongyaodxc.cs.weekcard20",ProductId_rygs="com.rongyaogs.cs.weekcard20",type=2},
[30] = {ID=30,RMB=20,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard30",ProductId_rydxc="com.rongyaodxc.cs.weekcard30",ProductId_rygs="com.rongyaogs.cs.weekcard30",type=2},
[40] = {ID=40,RMB=100,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard40",ProductId_rydxc="com.rongyaodxc.cs.weekcard40",ProductId_rygs="com.rongyaogs.cs.weekcard40",type=2},
[50] = {ID=50,RMB=20,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard50",ProductId_rydxc="com.rongyaodxc.cs.weekcard50",ProductId_rygs="com.rongyaogs.cs.weekcard50",type=2},
[60] = {ID=60,RMB=100,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard60",ProductId_rydxc="com.rongyaodxc.cs.weekcard60",ProductId_rygs="com.rongyaogs.cs.weekcard60",type=2},
[70] = {ID=70,RMB=50,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard70",ProductId_rydxc="com.rongyaodxc.cs.weekcard70",ProductId_rygs="com.rongyaogs.cs.weekcard70",type=2},
[80] = {ID=80,RMB=200,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard80",ProductId_rydxc="com.rongyaodxc.cs.weekcard80",ProductId_rygs="com.rongyaogs.cs.weekcard80",type=2},
[90] = {ID=90,RMB=50,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard90",ProductId_rydxc="com.rongyaodxc.cs.weekcard90",ProductId_rygs="com.rongyaogs.cs.weekcard90",type=2},
[100] = {ID=100,RMB=200,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard100",ProductId_rydxc="com.rongyaodxc.cs.weekcard100",ProductId_rygs="com.rongyaogs.cs.weekcard100",type=2},
[110] = {ID=110,RMB=50,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard110",ProductId_rydxc="com.rongyaodxc.cs.weekcard110",ProductId_rygs="com.rongyaogs.cs.weekcard110",type=2},
[120] = {ID=120,RMB=200,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard120",ProductId_rydxc="com.rongyaodxc.cs.weekcard120",ProductId_rygs="com.rongyaogs.cs.weekcard120",type=2},
[130] = {ID=130,RMB=100,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard130",ProductId_rydxc="com.rongyaodxc.cs.weekcard130",ProductId_rygs="com.rongyaogs.cs.weekcard130",type=2},
[140] = {ID=140,RMB=200,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard140",ProductId_rydxc="com.rongyaodxc.cs.weekcard140",ProductId_rygs="com.rongyaogs.cs.weekcard140",type=2},
[150] = {ID=150,RMB=100,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard150",ProductId_rydxc="com.rongyaodxc.cs.weekcard150",ProductId_rygs="com.rongyaogs.cs.weekcard150",type=2},
[160] = {ID=160,RMB=200,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard160",ProductId_rydxc="com.rongyaodxc.cs.weekcard160",ProductId_rygs="com.rongyaogs.cs.weekcard160",type=2},
[170] = {ID=170,RMB=100,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard170",ProductId_rydxc="com.rongyaodxc.cs.weekcard170",ProductId_rygs="com.rongyaogs.cs.weekcard170",type=2},
[180] = {ID=180,RMB=200,Reward=0,SpecialReward=0,icon="UI_activity_monthcard.png",ProductId_ry="com.rongyao.cs.weekcard180",ProductId_rydxc="com.rongyaodxc.cs.weekcard180",ProductId_rygs="com.rongyaogs.cs.weekcard180",type=2},
}
return recharge
