local language = {
[1] = {id=1,enumid="Err_system",zh_ch="系统出错",zh_tw="",en="",ja="",ko=""},
[2] = {id=2,enumid="Err_conn_lost",zh_ch="与服务器断开连接",zh_tw="",en="",ja="",ko=""},
[3] = {id=3,enumid="Err_conn_replace",zh_ch="连线被取代",zh_tw="",en="",ja="",ko=""},
[5] = {id=5,enumid="Err_metiral",zh_ch="金币不足",zh_tw="",en="",ja="",ko=""},
[6] = {id=6,enumid="Err_upgrade_lv",zh_ch="强化等级不可超过玩家等级",zh_tw="",en="",ja="",ko=""},
[7] = {id=7,enumid="Err_upgrade_equip_lv",zh_ch="强化等级不足, 请先提升强化等级",zh_tw="",en="",ja="",ko=""},
[8] = {id=8,enumid="Err_upgrade_equip_quality",zh_ch="请先锻造, 提升品质后再进行强化",zh_tw="",en="",ja="",ko=""},
[10002] = {id=10002,enumid="eLan_cm_level",zh_ch="等级",zh_tw="",en="",ja="",ko=""},
[10003] = {id=10003,enumid="eLan_cm_bangpai",zh_ch="帮派",zh_tw="",en="",ja="",ko=""},
[10004] = {id=10004,enumid="eLan_cm_system",zh_ch="系统",zh_tw="",en="",ja="",ko=""},
[10005] = {id=10005,enumid="eLan_cm_occup",zh_ch="职业",zh_tw="",en="",ja="",ko=""},
[10006] = {id=10006,enumid="eLan_cm_addFriend",zh_ch="加为好友",zh_tw="",en="",ja="",ko=""},
[54074] = {id=54074,enumid="eLan_chat_showItemTip",zh_ch="查看物品详细信息",zh_tw="",en="",ja="",ko=""},
[54075] = {id=54075,enumid="eLan_chat_mainroleselect",zh_ch="你要选择的是 :",zh_tw="",en="",ja="",ko=""},
[54076] = {id=54076,enumid="eLan_chat_seletprivate",zh_ch="与该玩家聊天",zh_tw="",en="",ja="",ko=""},
[54077] = {id=54077,enumid="eLan_chat_world",zh_ch="世界",zh_tw="",en="",ja="",ko=""},
[54078] = {id=54078,enumid="eLan_chat_privates",zh_ch="密语",zh_tw="",en="",ja="",ko=""},
[54080] = {id=54080,enumid="eLan_chat_send",zh_ch="发送",zh_tw="",en="",ja="",ko=""},
[54081] = {id=54081,enumid="eLan_chat_addItem",zh_ch="",zh_tw="",en="",ja="",ko=""},
[54082] = {id=54082,enumid="eLan_talent_title",zh_ch="心法",zh_tw="",en="",ja="",ko=""},
[54083] = {id=54083,enumid="eLan_chat_title",zh_ch="聊天",zh_tw="",en="",ja="",ko=""},
}
return language
