local roleoccup = {
[10] = {ID=10,name="剑客",index=1,appear="zs",gender=0,icon="headPlayer01.png"},
[11] = {ID=11,name="狂战",index=0,appear="zs",gender=0,icon=""},
[12] = {ID=12,name="鬼阵",index=0,appear="zs",gender=0,icon=""},
[13] = {ID=13,name="魔剑士",index=0,appear="zs",gender=0,icon=""},
[20] = {ID=20,name="枪炮师",index=2,appear="zs",gender=1,icon="headPlayer01.png"},
[21] = {ID=21,name="神枪手",index=0,appear="zs",gender=0,icon=""},
[22] = {ID=22,name="弹药专家",index=0,appear="zs",gender=0,icon=""},
[23] = {ID=23,name="机械师",index=0,appear="zs",gender=0,icon=""},
[30] = {ID=30,name="拳法家",index=0,appear="zs",gender=0,icon=""},
[31] = {ID=31,name="流氓",index=0,appear="zs",gender=0,icon=""},
[32] = {ID=32,name="气功师",index=0,appear="zs",gender=0,icon=""},
[33] = {ID=33,name="柔道",index=0,appear="zs",gender=0,icon=""},
[40] = {ID=40,name="战斗法师",index=0,appear="zs",gender=0,icon=""},
[41] = {ID=41,name="元素法师",index=0,appear="zs",gender=0,icon=""},
[42] = {ID=42,name="召唤师",index=0,appear="zs",gender=0,icon=""},
[43] = {ID=43,name="魔道学者",index=0,appear="zs",gender=0,icon=""},
[50] = {ID=50,name="牧师",index=0,appear="zs",gender=0,icon=""},
[51] = {ID=51,name="圣骑士",index=0,appear="zs",gender=0,icon=""},
[52] = {ID=52,name="驱魔师",index=0,appear="zs",gender=0,icon=""},
[53] = {ID=53,name="圣言者",index=0,appear="zs",gender=0,icon=""},
[60] = {ID=60,name="刺客",index=0,appear="zs",gender=0,icon=""},
[61] = {ID=61,name="术士",index=0,appear="zs",gender=0,icon=""},
[62] = {ID=62,name="忍者",index=0,appear="zs",gender=0,icon=""},
[63] = {ID=63,name="盗贼",index=0,appear="zs",gender=0,icon=""},
}
return roleoccup
