local uisounds = {
[1] = {ID=1,soundfile="music/effect/button_1.mp3",details="刚进入游戏公告对话框的“我知道了”按钮"},
[2] = {ID=2,soundfile="music/effect/button_1.mp3",details="选择服务器界面“进入游戏”按钮"},
[3] = {ID=3,soundfile="music/effect/button_1.mp3",details="选择服务器界面“快速登录”按钮"},
[4] = {ID=4,soundfile="music/effect/button_1.mp3",details="快速登录界面中的，“注册”按钮"},
[5] = {ID=5,soundfile="music/effect/button_1.mp3",details="快速登录界面中的，“登录”按钮"},
[6] = {ID=6,soundfile="music/effect/role_change.mp3",details="创建角色界面左右滑动切换角色时的音效"},
[7] = {ID=7,soundfile="music/effect/button_1.mp3",details="创建角色界面中，“创建角色”按钮"},
[8] = {ID=8,soundfile="music/effect/button_1.mp3",details="角色取名界面中的“确定”按钮"},
[9] = {ID=9,soundfile="music/effect/button_1.mp3",details="创建好角色后选择角色界面“开始游戏”按钮"},
[10] = {ID=10,soundfile="music/effect/button_1.mp3",details="主城界面点击“招募”icon"},
[11] = {ID=11,soundfile="music/effect/button_1.mp3",details="主城界面点击“天梯”icon"},
[12] = {ID=12,soundfile="music/effect/button_1.mp3",details="主城界面点击“挑战赛”icon"},
[13] = {ID=13,soundfile="music/effect/button_1.mp3",details="主城界面点击“任务”icon"},
[14] = {ID=14,soundfile="music/effect/button_2.mp3",details="主城界面点击任意NPC都播放此音效"},
[15] = {ID=15,soundfile="music/effect/button_4.mp3",details="主城界面点击右下角的icon主按钮"},
[16] = {ID=16,soundfile="music/effect/button_1.mp3",details="主城界面主按钮中的“角色”按钮"},
[17] = {ID=17,soundfile="music/effect/button_1.mp3",details="主城界面主按钮中的“武器”按钮"},
[18] = {ID=18,soundfile="music/effect/button_1.mp3",details="主城界面主按钮中的“技能”按钮"},
[19] = {ID=19,soundfile="music/effect/button_1.mp3",details="主城界面主按钮中的“阵容”按钮"},
[20] = {ID=20,soundfile="music/effect/button_1.mp3",details="主城界面主按钮中的“训练”按钮"},
[21] = {ID=21,soundfile="music/effect/button_1.mp3",details="主城界面主按钮中的“邮件”按钮"},
[22] = {ID=22,soundfile="music/effect/button_1.mp3",details="人物背包界面中点击“装备”页签"},
[23] = {ID=23,soundfile="music/effect/button_1.mp3",details="人物背包界面中点击“技能”页签"},
[24] = {ID=24,soundfile="music/effect/button_1.mp3",details="人物背包界面中点击“仓库”页签"},
[25] = {ID=25,soundfile="music/effect/skill_levelup.mp3",details="人物技能页签中，可以点的橙色“升级”按钮（按钮灰色时不用）"},
[26] = {ID=26,soundfile="music/effect/button_5.mp3",details="武器强化界面“强化”按钮"},
[27] = {ID=27,soundfile="music/effect/change_card.mp3",details="武器强化界面滑动卡牌效果音效（每滑动一次播放一次）"},
[28] = {ID=28,soundfile="music/effect/button_5.mp3",details="武器锻造界面“锻造”按钮"},
[29] = {ID=29,soundfile="music/effect/button_3.mp3",details="合成装备界面“合成”按钮"},
[30] = {ID=30,soundfile="music/effect/button_1.mp3",details="阵容界面“组队”页签"},
[31] = {ID=31,soundfile="music/effect/button_1.mp3",details="阵容界面“详情”页签"},
[32] = {ID=32,soundfile="music/effect/button_1.mp3",details="阵容界面“技能”页签"},
[33] = {ID=33,soundfile="",details="阵容界面组队页签界面中“加入”按钮"},
[34] = {ID=34,soundfile="",details="阵容界面组队页签界面中“卸下”按钮"},
[35] = {ID=35,soundfile="music/effect/skill_levelup.mp3",details="阵容界面技能页签界面中选择技能“升级”按钮"},
[36] = {ID=36,soundfile="music/effect/button_3.mp3",details="训练界面“训练”按钮"},
[37] = {ID=37,soundfile="music/effect/button_3.mp3",details="突破界面“突破极限”按钮"},
[38] = {ID=38,soundfile="music/effect/equip_levelup.mp3",details="点击训练成功后，当即播放成功音效"},
[39] = {ID=39,soundfile="music/effect/equip_levelup.mp3",details="点击突破极限成功后，当即播放的成功音效"},
[40] = {ID=40,soundfile="music/effect/button_1.mp3",details="俱乐部挑战赛界面点击每个“挑战”按钮"},
[41] = {ID=41,soundfile="music/effect/button_3.mp3",details="俱乐部挑战赛对阵界面点击“开始战斗”按钮，"},
[42] = {ID=42,soundfile="music/effect/fight_ready.mp3",details="俱乐部挑战赛点击\"挑战\"后"},
[43] = {ID=43,soundfile="music/effect/button_3.mp3",details="俱乐部挑战赛界面点击“刷新”按钮"},
[44] = {ID=44,soundfile="music/effect/button_3.mp3",details="荣耀天梯界面“寻找对手”按钮"},
[45] = {ID=45,soundfile="music/effect/fight_ready.mp3",details="荣耀天梯界面“寻找对手”按钮点击后，进入对阵界面当即播放的音效"},
[46] = {ID=46,soundfile="music/effect/button_3.mp3",details="天梯对阵界面 “开始战斗” 按钮"},
[47] = {ID=47,soundfile="music/effect/button_1.mp3",details="招募界面“派出普通探员”按钮"},
[48] = {ID=48,soundfile="music/effect/button_1.mp3",details="招募界面“派出高级探员”按钮"},
[49] = {ID=49,soundfile="music/effect/button_3.mp3",details="招募界面“派出普通探员”按钮->>“购买一次”，按钮"},
[50] = {ID=50,soundfile="music/effect/button_1.mp3",details="招募界面“派出高级探员”按钮->>“购买一次”按钮"},
[51] = {ID=51,soundfile="music/effect/button_1.mp3",details="招募界面“派出高级探员”按钮->>“购买10次”按钮"},
[52] = {ID=52,soundfile="music/effect/coin_cost.mp3",details="招募界面花掉金币的“购买一次”按钮点击后，随即播放该金币消费音效"},
[53] = {ID=53,soundfile="music/effect/diamond_cost.mp3",details="招募界面花掉钻石的“购买一次”按钮点击后，随即播放该钻石消费音效"},
[54] = {ID=54,soundfile="music/effect/spread_card.mp3",details="抽卡时出现卡牌当即音效"},
[55] = {ID=55,soundfile="music/effect/rare_card.mp3",details="抽卡时出现稀有卡当即音效"},
[56] = {ID=56,soundfile="music/effect/spread_card.mp3",details="十连抽，每张卡出现都出音效"},
[57] = {ID=57,soundfile="music/effect/button_1.mp3",details="关卡地图选关界面点击关卡，“扫荡”按钮"},
[58] = {ID=58,soundfile="music/effect/button_1.mp3",details="关卡地图选关界面点击关卡，“挑战”按钮"},
[59] = {ID=59,soundfile="music/effect/experience_bar.mp3",details="战斗场景中，战斗胜利的结算同时，经验条走动当即播放音效"},
[60] = {ID=60,soundfile="music/effect/balance.mp3",details="战斗场景中，战斗胜利的结算同时，金币数值跳动同时播放音效"},
[61] = {ID=61,soundfile="music/effect/turn_on_card.mp3",details="战斗场景中，结算后翻牌，点击牌音效"},
[62] = {ID=62,soundfile="music/effect/level_up.mp3",details="任何界面中，翅膀人物升级特效当即播放"},
[63] = {ID=63,soundfile="music/effect/victory.mp3",details="战斗胜利时随即播放此音乐，不需循环。"},
[64] = {ID=64,soundfile="music/effect/defeat.mp3",details="战斗失败时随即播放次音乐，同63战斗胜利"},
[65] = {ID=65,soundfile="music/effect/relaxation.mp3",details="在胜利音效victory.mp3 播放结束后即刻 播放relaxation.mp3播放此音乐为一直循环的，直到跳转到其他界面。"},
[66] = {ID=66,soundfile="music/effect/button_1.mp3",details="主城->任务界面->点击日常或者主线界面中的 \"前往\"按钮"},
[67] = {ID=67,soundfile="music/effect/skill_levelup.mp3",details="主城->任务界面->点击日常或者主线界面中的 \"可领取\"按钮"},
[68] = {ID=68,soundfile="music/effect/fight.mp3",details="\"天梯和挑战赛战斗场景界面,配合显示fight的时候播放\""},
[69] = {ID=69,soundfile="music/effect/turn_card.mp3",details="\"阵容界面,点击按住卡牌即播放(从队伍中点击按住或者从下面一排的卡牌中点击按住都用这个音效)\""},
[70] = {ID=70,soundfile="music/effect/vip_draw_cards.mp3",details="\"抽卡界面,VIP抽卡无论是抽一次,或者十连抽,点击后出现出卡特效即播放此段音效\""},
}
return uisounds
